services:
  webapp:
    build: .
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_DATA_PROTECTION__REPOSITORY_TYPE: "None"
      ConnectionStrings__PostgreSQL: "Host=db;Port=5432;Database=database;Username=postgres;Password=rootroot"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - aspnet_dataprotection_keys:/root/.aspnet/DataProtection-Keys

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: database
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data

volumes:
  aspnet_dataprotection_keys:
  pg_data: